### ISSUE TITLE
comparações múltiplas e resolução de comparações

### ISSUE THREAD

**Issue by NiumXp** [wendrewdevelop/python4noobs#15]
O tópico sobre [comparações](https://github.com/wendrewdevelop/python4noobs/blob/master/Expressões/comparacoes.md) não fala sobre comparações "múltiplas" e como o Python as resolve, acredito que abordar isso seja de extrema relevância.

Nessa parte da [documentação](https://docs.python.org/3/reference/expressions.html#comparisons), nesse paragrafo:

**"Comparisons can be chained arbitrarily, e.g., x < y <= z is equivalent to x < y and y <= z, except that y is evaluated only once (but in both cases z is not evaluated at all when x < y is found to be false)."**

é dito que as comparações podem ser ordenadas arbitrariamente da seguinte forma, `x == y != z`, isso não é dito no tópico.

Essa outra parte da documentação:

**Unlike C, all comparison operations in Python have the same priority, which is lower than that of any arithmetic, shifting or bitwise operation. Also unlike C, expressions like a < b < c have the interpretation that is conventional in mathematics:**

também é bastante importante, pois diz como as comparações são resolvidas.

**Comment by wendrewdevelop** [comment]
https://github.com/wendrewdevelop/python4noobs/commit/5b10eb3c48f6cc651bf7e8fa29cb349134eb8746
