### ISSUE TITLE
[Debate] Estruturas de dados

### ISSUE THREAD

**Issue by dunossauro** [wendrewdevelop/python4noobs#18]
O tópico 3 é definido como "Estruturas de dados".

O debate começa pra mim quando pensamos em 'int' ou tipos numéricos como estruturas de dados. O [datamodel](https://docs.python.org/3/reference/datamodel.html#the-standard-type-hierarchy) define como *Tipos*, o que eu considero ser mais eficiente a ponto de demonstração. Existe um debate claro se Int é ou não uma estrutura.

Um exemplo é ver como números aparecem na seção de tipos https://docs.python.org/3/library/stdtypes.html, assim como as sequências, porém somente as sequências são contempladas na página de estruturas: https://docs.python.org/3/tutorial/datastructures.html

Acredito que utilizar como tipos, possa ser mais proveitoso para um iniciante, pois além de não gerar confusão e é coerente com os termos escolhidos pela documentação.

**Comment by wendrewdevelop** [comment]
Du, obrigado (novamente).

Sinceramente não sei onde estava com a cabeça de colocar isso como "Estruturas de dados". Substitui por "Tipos", acho que condiz melhor com a doc do python.

https://github.com/wendrewdevelop/python4noobs/commit/e8e928d4cfa1e264c0b842d3ca457012226e13ac
