### ISSUE TITLE
[Debate] Estruturas de condição.

### ISSUE THREAD

**Issue by dunossauro** [wendrewdevelop/python4noobs#19]
Estruturas de condição é um nome confuso, mesmo se optar por essa nomenclatura, acredito que "estruturas de decisão" faria mais sentido. Ou até mesmo controle de fluxo.

Porém, a gramática define esse bloco de instruções como [Instruções compostas](https://docs.python.org/3/reference/compound_stmts.html). Que vão de definições até controle de fluxo:

```
compound_stmt ::=  if_stmt
                   | while_stmt
                   | for_stmt
                   | try_stmt
                   | with_stmt
                   | funcdef
                   | classdef
                   | async_with_stmt
                   | async_for_stmt
                   | async_funcdef
suite         ::=  stmt_list NEWLINE | NEWLINE INDENT statement+ DEDENT
statement     ::=  stmt_list NEWLINE | compound_stmt
stmt_list     ::=  simple_stmt (";" simple_stmt)* [";"]
```

**Comment by dunossauro** [comment]
Um dos motivos que acredito que "Condição" não contempla a totalidade é que tanto `try` quanto `with` não são decisões, são controles de fluxo.

**Comment by wendrewdevelop** [comment]
Valeu, Du. 

Finalmente, consegui um tempo pra voltar a mexer no github. Demorei, mas cheguei rapido.

Mudei o termo "Estrutura de condição" para "Controle de fluxo", realmente faz mais sentido.

https://github.com/wendrewdevelop/python4noobs/commit/cdf46244e4884f5d7f15318030aa79d5da89288a
