### ISSUE TITLE
link das conversoes arimeticas esta errado

### ISSUE THREAD

**Issue by leosegate** [wendrewdevelop/python4noobs#20]
link certo: https://github.com/wendrewdevelop/python4noobs/blob/master/Express%C3%B5es/express%C3%B5es_aritm%C3%A9ticas.md

**Comment by wendrewdevelop** [comment]
Problema corrigido. 
Obrigado!

https://github.com/wendrewdevelop/python4noobs/commit/825d579c400d783275195322a721e2ed35693a6a
