### ISSUE TITLE
link interfaces graficas tkinter errado

### ISSUE THREAD

**Issue by leosegate** [wendrewdevelop/python4noobs#21]
https://github.com/wendrewdevelop/python4noobs/blob/master/M%C3%B3dulo-Tkinter/interfaces_graficas_tkinter.md

**Comment by wendrewdevelop** [comment]
Obrigado!

Corrigido: https://github.com/wendrewdevelop/python4noobs/commit/ac07f6fec5534b2b5016bf5f7cea179a8497b34b
