### ISSUE TITLE
Alteração de caracter em termo utilizado.

### ISSUE THREAD

**Issue by ThiagoPinto87** [wendrewdevelop/python4noobs#25]
No item 7.
No link que fala sobre escrever no arquivo com Python, o texto descreve o seguinte...
_"A lista é um objeto iterável, então podemos passa-la como parâmetro do método writelines(). Utilizamos, também, o \n para saltar a linha ao escrevê-la no arquivo. Com isso, o resultado será o seguinte:"_

Ocorre que no texto, ele informa que para saltar a linha, utiliza-se o contra-barra e "n".
Porém no texto está aparecendo como pipe "|".

Espero ter contribuído positivamente.

**Comment by wendrewdevelop** [comment]
@ThiagoPinto87  Obrigado pela colaboração, irei atualizar esse item.

**Comment by ThiagoPinto87** [comment]
Tmj
