### ISSUE TITLE
Link do Módulo TKinter

### ISSUE THREAD

**Issue by Edclydson** [wendrewdevelop/python4noobs#26]
Ao final do módulo hello_world, mais especificamente na parte: 
> *Agora que ja temos uma base, podemos ir para o [proximo passo](https://github.com/wendrewdevelop/python4noobs/blob/master/M%C3%B3dulo-Tkinter/atributos_padrao.md) e conhecer os atributos padrões do tkinter.*

O link não redireciona para a próxima parte, e qual seria a próxima parte? widgets_tkinter ou posicionamento_atributos ?

**Comment by wendrewdevelop** [comment]
Fixed: https://github.com/wendrewdevelop/python4noobs/commit/ff770fee59324d55e43781a6d44d7a66a2c4c010
