### ISSUE TITLE
Aplicar licença no repositório

### ISSUE THREAD

**Issue by lissarubi** [wendrewdevelop/python4noobs#5]
Por gentileza eu peço que algum dos contribuidores coloque uma licença no repositório, como a licença MIT, pois assim, ficará garantido que todo o conteúdo do repositório e livre e qualquer pessoa pode ler, modificar, redistribuir,etc. Obrigado.

**Comment by wendrewdevelop** [comment]
Pull request successfully merged and closed.

Arquivo adicionado.
