### ISSUE TITLE
Adicionar seção sobre Zen of Python

### ISSUE THREAD

**Issue by Ronkiro** [wendrewdevelop/python4noobs#7]
É um requisito quase que obrigatório que todo Pythonista conheça a Zen of Python.

https://www.python.org/dev/peps/pep-0020/

**Comment by wendrewdevelop** [comment]
Issue fechada.
Commit realizado: https://github.com/wendrewdevelop/python4noobs/commit/44f44192c22e71d5da44ea64c3af2501ab4fc185
