### ISSUE TITLE
Adicionar seção sobre magic methods

### ISSUE THREAD

**Issue by Ronkiro** [wendrewdevelop/python4noobs#8]
Esse é um conceito um pouco mais avançado de Python que permite que códigos sejam mais Pythonicos, acho crucial para o projeto.

https://towardsdatascience.com/magic-methods-in-python-by-example-16b6826cae5c

**Comment by wendrewdevelop** [comment]
Issue resolvido e fechada.

commit: https://github.com/wendrewdevelop/python4noobs/commit/e43e94891bc77bf422c68082a2b7a69a0620d3e7
