### ISSUE TITLE
Adicionar informação sobre objetos em Python

### ISSUE THREAD

**Issue by Ronkiro** [wendrewdevelop/python4noobs#9]
Acho interessante adicionar informações sobre como os objetos em Python funcionam, em conjunto com a sugestão dos Magic Methods.

Em resumo: https://codesachin.wordpress.com/2016/06/09/the-magic-behind-attribute-access-in-python/#:~:text=The%20__dict__%20attribute,attribute%20name%20to%20its%20value.

A função de slots, por exemplo, pode ser crucial caso o leitor vá para uma área onde o uso de recursos é crítico.

**Comment by wendrewdevelop** [comment]
Resumo sobre objetos: https://github.com/wendrewdevelop/python4noobs/commit/febdbdb2a6364da3bed5a51bacdca8d12c09913f

Função slots acrescentada: https://github.com/wendrewdevelop/python4noobs/commit/b25855e73a4d5f48c48d803e7d2b4edefe987d79
